<a href="https://colab.research.google.com/github/kellllyyy/mase/blob/main/tutorial_2_lora_finetune.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tutorial 2: Finetuning Bert for Sequence Classification using a LoRA adapter

When we import a pretrained transformer model from HuggingFace, we receive the encoder/decoder weights, which aren't that useful on their own - to perform a useful task such as sequence classification, we add a classification head on top of the model and train those weights on the required dataset. In this tutorial, we'll look at fine tuning a Bert model for sequence classification with two approaches. First, we'll attempt full Supervised Fine Tuning (SFT). Then, we'll use the Mase stack to add a [LoRA](https://arxiv.org/abs/2106.09685) adapter to the model. We'll look at the effect in memory requirement for training and the achieved accuracy.

In [1]:
%pip uninstall -y optimum transformers datasets evaluate fsspec
%pip install optimum==1.24.0 transformers==4.51 datasets==3.3.2 evaluate==0.4.3 fsspec==2024.12.0

WARNING: Skipping optimum as it is not installed.
Found existing installation: transformers 4.57.6
Uninstalling transformers-4.57.6:
  Successfully uninstalled transformers-4.57.6
Found existing installation: datasets 4.0.0
Uninstalling datasets-4.0.0:
  Successfully uninstalled datasets-4.0.0
WARNING: Skipping evaluate as it is not installed.
Found existing installation: fsspec 2025.3.0
Uninstalling fsspec-2025.3.0:
  Successfully uninstalled fsspec-2025.3.0
Collecting optimum==1.24.0
  Downloading optimum-1.24.0-py3-none-any.whl.metadata (21 kB)
Collecting transformers==4.51
  Downloading transformers-4.51.0-py3-none-any.whl.metadata (38 kB)
Collecting datasets==3.3.2
  Downloading datasets-3.3.2-py3-none-any.whl.metadata (19 kB)
Collecting evaluate==0.4.3
  Downloading evaluate-0.4.3-py3-none-any.whl.metadata (9.2 kB)
Collecting fsspec==2024.12.0
  Downloading fsspec-2024.12.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: torch>=1.11 in /usr/local/lib/python3.12/dist-packages (from optimum==1.24.0) (2.9.0+cu126)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from optimum==1.24.0) (25.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optimum==1.24.0) (2.0.2)
Requirement already satisfied: huggingface-hub>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from optimum==1.24.0) (0.36.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers==4.51) (3.20.3)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.51) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.51) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers==4.51) (2.32.4)
Collecting tokenizers<0.22,>=0.21 (from transformers==4.51)
  Downloading tokenizers-0.21.4-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers==4.51) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers==4.51) (4.67.1)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets==3.3.2) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets==3.3.2) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets==3.3.2) (2.2.2)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets==3.3.2) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets==3.3.2) (0.70.16)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.12/dist-packages (from datasets==3.3.2) (3.13.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets==3.3.2) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets==3.3.2) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets==3.3.2) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets==3.3.2) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets==3.3.2) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets==3.3.2) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets==3.3.2) (1.22.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.8.0->optimum==1.24.0) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.8.0->optimum==1.24.0) (1.2.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.51) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.51) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.51) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.51) (2026.1.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11->optimum==1.24.0) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11->optimum==1.24.0) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11->optimum==1.24.0) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11->optimum==1.24.0) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11->optimum==1.24.0) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11->optimum==1.24.0) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11->optimum==1.24.0) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11->optimum==1.24.0) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11->optimum==1.24.0) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11->optimum==1.24.0) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11->optimum==1.24.0) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11->optimum==1.24.0) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11->optimum==1.24.0) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11->optimum==1.24.0) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11->optimum==1.24.0) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11->optimum==1.24.0) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11->optimum==1.24.0) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11->optimum==1.24.0) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11->optimum==1.24.0) (1.11.1.6)
Requirement already satisfied: triton==3.5.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11->optimum==1.24.0) (3.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets==3.3.2) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets==3.3.2) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets==3.3.2) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets==3.3.2) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11->optimum==1.24.0) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11->optimum==1.24.0) (3.0.3)
Downloading optimum-1.24.0-py3-none-any.whl (433 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 433.6/433.6 kB 30.9 MB/s eta 0:00:00
Downloading transformers-4.51.0-py3-none-any.whl (10.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.4/10.4 MB 100.5 MB/s eta 0:00:00
Downloading datasets-3.3.2-py3-none-any.whl (485 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 485.4/485.4 kB 23.2 MB/s eta 0:00:00
Downloading evaluate-0.4.3-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.0/84.0 kB 8.6 MB/s eta 0:00:00
Downloading fsspec-2024.12.0-py3-none-any.whl (183 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 183.9/183.9 kB 19.7 MB/s eta 0:00:00
Downloading tokenizers-0.21.4-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 100.2 MB/s eta 0:00:00
Installing collected packages: fsspec, tokenizers, transformers, datasets, optimum, evaluate
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.22.2
    Uninstalling tokenizers-0.22.2:
      Successfully uninstalled tokenizers-0.22.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gcsfs 2025.3.0 requires fsspec==2025.3.0, but you have fsspec 2024.12.0 which is incompatible.
Successfully installed datasets-3.3.2 evaluate-0.4.3 fsspec-2024.12.0 optimum-1.24.0 tokenizers-0.21.4 transformers-4.51.0

In [2]:
%pip install \
black toml GitPython colorlog \
cocotb==1.9.2 pybind11 \
timm pytorch-nlp sentencepiece einops kornia \
hyperopt@git+https://github.com/hyperopt/hyperopt.git \
optuna stable-baselines3[extra] \
tensorboard tensorboardx wandb lightning pytorch-lightning \
bitarray "bitstring>=4.2" attr-dot-dict emoji \
onnx onnxruntime onnxconverter-common accelerate \
absl-py prettytable pynvml py-cpuinfo psutil cvxpy pydot \
h5py imageio imageio-ffmpeg \
opencv-python matplotlib scikit-learn pandas \
sphinx-rtd-theme "sphinx-needs>=4" \
sphinx-test-reports@git+https://github.com/useblocks/sphinx-test-reports \
sphinxcontrib-plantuml sphinx-glpi-theme \
ghp-import myst_parser myst-nb sphinx-book-theme \
ultralytics==8.3.235

Collecting hyperopt@ git+https://github.com/hyperopt/hyperopt.git
  Cloning https://github.com/hyperopt/hyperopt.git to /tmp/pip-install-b7vvf2v3/hyperopt_e87f1a73e9d54213aa1c3ad2f6cd9b5b
  Running command git clone --filter=blob:none --quiet https://github.com/hyperopt/hyperopt.git /tmp/pip-install-b7vvf2v3/hyperopt_e87f1a73e9d54213aa1c3ad2f6cd9b5b
  Resolved https://github.com/hyperopt/hyperopt.git to commit 0658f680c84a313eaffe1771a20dfe2ebabd7fd4
  Preparing metadata (setup.py) ... done
Collecting sphinx-test-reports@ git+https://github.com/useblocks/sphinx-test-reports
  Cloning https://github.com/useblocks/sphinx-test-reports to /tmp/pip-install-b7vvf2v3/sphinx-test-reports_058892d4b0bf43f99f5547eb847f510f
  Running command git clone --filter=blob:none --quiet https://github.com/useblocks/sphinx-test-reports /tmp/pip-install-b7vvf2v3/sphinx-test-reports_058892d4b0bf43f99f5547eb847f510f
  Resolved https://github.com/useblocks/sphinx-test-reports to commit 97df9daec4a50800ecb5cfdcd5a49416840750bf
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting black
  Downloading black-26.1.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (88 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.9/88.9 kB 6.3 MB/s eta 0:00:00
Requirement already satisfied: toml in /usr/local/lib/python3.12/dist-packages (0.10.2)
Requirement already satisfied: GitPython in /usr/local/lib/python3.12/dist-packages (3.1.46)
Collecting colorlog
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Collecting cocotb==1.9.2
  Downloading cocotb-1.9.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.9 kB)
Collecting pybind11
  Downloading pybind11-3.0.1-py3-none-any.whl.metadata (10.0 kB)
Requirement already satisfied: timm in /usr/local/lib/python3.12/dist-packages (1.0.24)
Collecting pytorch-nlp
  Downloading pytorch_nlp-0.5.0-py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.12/dist-packages (0.2.1)
Requirement already satisfied: einops in /usr/local/lib/python3.12/dist-packages (0.8.2)
Collecting kornia
  Downloading kornia-0.8.2-py2.py3-none-any.whl.metadata (18 kB)
Collecting optuna
  Downloading optuna-4.7.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: tensorboard in /usr/local/lib/python3.12/dist-packages (2.19.0)
Collecting tensorboardx
  Downloading tensorboardx-2.6.4-py3-none-any.whl.metadata (6.2 kB)
Requirement already satisfied: wandb in /usr/local/lib/python3.12/dist-packages (0.24.0)
Collecting lightning
  Downloading lightning-2.6.1-py3-none-any.whl.metadata (44 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.8/44.8 kB 4.4 MB/s eta 0:00:00
Collecting pytorch-lightning
  Downloading pytorch_lightning-2.6.1-py3-none-any.whl.metadata (21 kB)
Collecting bitarray
  Downloading bitarray-3.8.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (34 kB)
Collecting bitstring>=4.2
  Downloading bitstring-4.3.1-py3-none-any.whl.metadata (5.3 kB)
Collecting attr-dot-dict
  Downloading attr_dot_dict-0.1.0-py3-none-any.whl.metadata (42 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.0/42.0 kB 4.2 MB/s eta 0:00:00
Collecting emoji
  Downloading emoji-2.15.0-py3-none-any.whl.metadata (5.7 kB)
Collecting onnx
  Downloading onnx-1.20.1-cp312-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Collecting onnxruntime
  Downloading onnxruntime-1.23.2-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (5.1 kB)
Collecting onnxconverter-common
  Downloading onnxconverter_common-1.16.0-py2.py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.12.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (1.4.0)
Requirement already satisfied: prettytable in /usr/local/lib/python3.12/dist-packages (3.17.0)
Collecting pynvml
  Downloading pynvml-13.0.1-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: py-cpuinfo in /usr/local/lib/python3.12/dist-packages (9.0.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (5.9.5)
Requirement already satisfied: cvxpy in /usr/local/lib/python3.12/dist-packages (1.6.7)
Requirement already satisfied: pydot in /usr/local/lib/python3.12/dist-packages (4.0.1)
Requirement already satisfied: h5py in /usr/local/lib/python3.12/dist-packages (3.15.1)
Requirement already satisfied: imageio in /usr/local/lib/python3.12/dist-packages (2.37.2)
Requirement already satisfied: imageio-ffmpeg in /usr/local/lib/python3.12/dist-packages (0.6.0)
Requirement already satisfied: opencv-python in /usr/local/lib/python3.12/dist-packages (4.13.0.90)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Collecting sphinx-rtd-theme
  Downloading sphinx_rtd_theme-3.1.0-py2.py3-none-any.whl.metadata (4.5 kB)
Collecting sphinx-needs>=4
  Downloading sphinx_needs-6.3.0-py3-none-any.whl.metadata (5.8 kB)
Collecting sphinxcontrib-plantuml
  Downloading sphinxcontrib_plantuml-0.31.tar.gz (15 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting sphinx-glpi-theme
  Downloading sphinx_glpi_theme-0.6-py2.py3-none-any.whl.metadata (1.8 kB)
Collecting ghp-import
  Downloading ghp_import-2.1.0-py3-none-any.whl.metadata (7.2 kB)
Collecting myst_parser
  Downloading myst_parser-5.0.0-py3-none-any.whl.metadata (5.6 kB)
Collecting myst-nb
  Downloading myst_nb-1.3.0-py3-none-any.whl.metadata (4.7 kB)
Collecting sphinx-book-theme
  Downloading sphinx_book_theme-1.1.4-py3-none-any.whl.metadata (5.8 kB)
Collecting ultralytics==8.3.235
  Downloading ultralytics-8.3.235-py3-none-any.whl.metadata (37 kB)
Collecting stable-baselines3[extra]
  Downloading stable_baselines3-2.7.1-py3-none-any.whl.metadata (4.8 kB)
Collecting find-libpython (from cocotb==1.9.2)
  Downloading find_libpython-0.5.0-py3-none-any.whl.metadata (2.8 kB)
Requirement already satisfied: numpy>=1.23.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics==8.3.235) (2.0.2)
Requirement already satisfied: pillow>=7.1.2 in /usr/local/lib/python3.12/dist-packages (from ultralytics==8.3.235) (11.3.0)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.12/dist-packages (from ultralytics==8.3.235) (6.0.3)
Requirement already satisfied: requests>=2.23.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics==8.3.235) (2.32.4)
Requirement already satisfied: scipy>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from ultralytics==8.3.235) (1.16.3)
Requirement already satisfied: torch>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics==8.3.235) (2.9.0+cu126)
Requirement already satisfied: torchvision>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics==8.3.235) (0.24.0+cu126)
Requirement already satisfied: polars>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics==8.3.235) (1.31.0)
Collecting ultralytics-thop>=2.0.18 (from ultralytics==8.3.235)
  Downloading ultralytics_thop-2.0.18-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from black) (8.3.1)
Collecting mypy-extensions>=0.4.3 (from black)
  Downloading mypy_extensions-1.1.0-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: packaging>=22.0 in /usr/local/lib/python3.12/dist-packages (from black) (25.0)
Collecting pathspec>=1.0.0 (from black)
  Downloading pathspec-1.0.4-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: platformdirs>=2 in /usr/local/lib/python3.12/dist-packages (from black) (4.5.1)
Collecting pytokens>=0.3.0 (from black)
  Downloading pytokens-0.4.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from GitPython) (4.0.12)
Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.12/dist-packages (from timm) (0.36.0)
Requirement already satisfied: safetensors in /usr/local/lib/python3.12/dist-packages (from timm) (0.7.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from pytorch-nlp) (4.67.1)
Collecting kornia_rs>=0.1.9 (from kornia)
  Downloading kornia_rs-0.1.10-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Requirement already satisfied: networkx>=2.2 in /usr/local/lib/python3.12/dist-packages (from hyperopt@ git+https://github.com/hyperopt/hyperopt.git) (3.6.1)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.12/dist-packages (from hyperopt@ git+https://github.com/hyperopt/hyperopt.git) (3.1.2)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.18.1)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.46)
Requirement already satisfied: gymnasium<1.3.0,>=0.29.1 in /usr/local/lib/python3.12/dist-packages (from stable-baselines3[extra]) (1.2.3)
Requirement already satisfied: pygame in /usr/local/lib/python3.12/dist-packages (from stable-baselines3[extra]) (2.6.1)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from stable-baselines3[extra]) (13.9.4)
Requirement already satisfied: ale-py>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from stable-baselines3[extra]) (0.11.2)
Requirement already satisfied: grpcio>=1.48.2 in /usr/local/lib/python3.12/dist-packages (from tensorboard) (1.76.0)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard) (3.10.1)
Requirement already satisfied: protobuf!=4.24.0,>=3.19.6 in /usr/local/lib/python3.12/dist-packages (from tensorboard) (5.29.5)
Requirement already satisfied: setuptools>=41.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard) (75.2.0)
Requirement already satisfied: six>1.9 in /usr/local/lib/python3.12/dist-packages (from tensorboard) (1.17.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard) (3.1.5)
Requirement already satisfied: pydantic<3 in /usr/local/lib/python3.12/dist-packages (from wandb) (2.12.3)
Requirement already satisfied: sentry-sdk>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from wandb) (2.51.0)
Requirement already satisfied: typing-extensions<5,>=4.8 in /usr/local/lib/python3.12/dist-packages (from wandb) (4.15.0)
Requirement already satisfied: fsspec<2028.0,>=2022.5.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<2028.0,>=2022.5.0->lightning) (2024.12.0)
Collecting lightning-utilities<2.0,>=0.10.0 (from lightning)
  Downloading lightning_utilities-0.15.2-py3-none-any.whl.metadata (5.7 kB)
Collecting torchmetrics<3.0,>0.7.0 (from lightning)
  Downloading torchmetrics-1.8.2-py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: ml_dtypes>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from onnx) (0.5.4)
Collecting coloredlogs (from onnxruntime)
  Downloading coloredlogs-15.0.1-py2.py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.12/dist-packages (from onnxruntime) (25.12.19)
Requirement already satisfied: sympy in /usr/local/lib/python3.12/dist-packages (from onnxruntime) (1.14.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prettytable) (0.5.0)
Requirement already satisfied: nvidia-ml-py>=12.0.0 in /usr/local/lib/python3.12/dist-packages (from pynvml) (13.590.48)
Requirement already satisfied: osqp>=0.6.2 in /usr/local/lib/python3.12/dist-packages (from cvxpy) (1.1.0)
Requirement already satisfied: clarabel>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from cvxpy) (0.11.1)
Requirement already satisfied: scs>=3.2.4.post1 in /usr/local/lib/python3.12/dist-packages (from cvxpy) (3.2.11)
Requirement already satisfied: pyparsing>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from pydot) (3.3.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.4.9)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: sphinx<10,>=6 in /usr/local/lib/python3.12/dist-packages (from sphinx-rtd-theme) (8.2.3)
Requirement already satisfied: docutils<0.23,>0.18 in /usr/local/lib/python3.12/dist-packages (from sphinx-rtd-theme) (0.21.2)
Collecting sphinxcontrib-jquery<5,>=4 (from sphinx-rtd-theme)
  Downloading sphinxcontrib_jquery-4.1-py2.py3-none-any.whl.metadata (2.6 kB)
Collecting requests-file~=2.1 (from sphinx-needs>=4)
  Downloading requests_file-2.1.0-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting jsonschema-rs~=0.37.1 (from sphinx-needs>=4)
  Downloading jsonschema_rs-0.37.4-cp310-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (21 kB)
Collecting sphinx-data-viewer~=0.1.5 (from sphinx-needs>=4)
  Downloading sphinx_data_viewer-0.1.5-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (from sphinx-test-reports@ git+https://github.com/useblocks/sphinx-test-reports) (6.0.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from myst_parser) (3.1.6)
Requirement already satisfied: markdown-it-py~=4.0 in /usr/local/lib/python3.12/dist-packages (from myst_parser) (4.0.0)
Requirement already satisfied: mdit-py-plugins~=0.5 in /usr/local/lib/python3.12/dist-packages (from myst_parser) (0.5.0)
Requirement already satisfied: importlib_metadata in /usr/local/lib/python3.12/dist-packages (from myst-nb) (8.7.1)
Requirement already satisfied: ipython in /usr/local/lib/python3.12/dist-packages (from myst-nb) (7.34.0)
Collecting jupyter-cache>=0.5 (from myst-nb)
  Downloading jupyter_cache-1.0.1-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: nbclient in /usr/local/lib/python3.12/dist-packages (from myst-nb) (0.10.4)
Requirement already satisfied: nbformat>=5.0 in /usr/local/lib/python3.12/dist-packages (from myst-nb) (5.10.4)
Requirement already satisfied: ipykernel in /usr/local/lib/python3.12/dist-packages (from myst-nb) (6.17.1)
Collecting pydata-sphinx-theme==0.15.4 (from sphinx-book-theme)
  Downloading pydata_sphinx_theme-0.15.4-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from pydata-sphinx-theme==0.15.4->sphinx-book-theme) (4.13.5)
Requirement already satisfied: Babel in /usr/local/lib/python3.12/dist-packages (from pydata-sphinx-theme==0.15.4->sphinx-book-theme) (2.17.0)
Requirement already satisfied: pygments>=2.7 in /usr/local/lib/python3.12/dist-packages (from pydata-sphinx-theme==0.15.4->sphinx-book-theme) (2.19.2)
Collecting accessible-pygments (from pydata-sphinx-theme==0.15.4->sphinx-book-theme)
  Downloading accessible_pygments-0.0.5-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.10)
Requirement already satisfied: cffi in /usr/local/lib/python3.12/dist-packages (from clarabel>=0.5.0->cvxpy) (2.0.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<2028.0,>=2022.5.0->lightning) (3.13.3)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->GitPython) (5.0.2)
Requirement already satisfied: farama-notifications>=0.0.1 in /usr/local/lib/python3.12/dist-packages (from gymnasium<1.3.0,>=0.29.1->stable-baselines3[extra]) (0.0.4)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface_hub->timm) (3.20.3)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub->timm) (1.2.0)
Requirement already satisfied: attrs in /usr/local/lib/python3.12/dist-packages (from jupyter-cache>=0.5->myst-nb) (25.4.0)
Requirement already satisfied: tabulate in /usr/local/lib/python3.12/dist-packages (from jupyter-cache>=0.5->myst-nb) (0.9.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py~=4.0->myst_parser) (0.1.2)
Requirement already satisfied: jupyter-client>=6.1.12 in /usr/local/lib/python3.12/dist-packages (from nbclient->myst-nb) (7.4.9)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from nbclient->myst-nb) (5.9.1)
Requirement already satisfied: traitlets>=5.4 in /usr/local/lib/python3.12/dist-packages (from nbclient->myst-nb) (5.7.1)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat>=5.0->myst-nb) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.12/dist-packages (from nbformat>=5.0->myst-nb) (4.26.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3->wandb) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3->wandb) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3->wandb) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.23.0->ultralytics==8.3.235) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.23.0->ultralytics==8.3.235) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.23.0->ultralytics==8.3.235) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.23.0->ultralytics==8.3.235) (2026.1.4)
Requirement already satisfied: sphinxcontrib-applehelp>=1.0.7 in /usr/local/lib/python3.12/dist-packages (from sphinx<10,>=6->sphinx-rtd-theme) (2.0.0)
Requirement already satisfied: sphinxcontrib-devhelp>=1.0.6 in /usr/local/lib/python3.12/dist-packages (from sphinx<10,>=6->sphinx-rtd-theme) (2.0.0)
Requirement already satisfied: sphinxcontrib-htmlhelp>=2.0.6 in /usr/local/lib/python3.12/dist-packages (from sphinx<10,>=6->sphinx-rtd-theme) (2.1.0)
Requirement already satisfied: sphinxcontrib-jsmath>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from sphinx<10,>=6->sphinx-rtd-theme) (1.0.1)

In [ ]:
import os
os.kill(os.getpid(), 9)

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import sys
sys.path.append('/content/drive/MyDrive/mase/src')
print(f"Added '/content/drive/MyDrive/mase/src' to sys.path")

Added '/content/drive/MyDrive/mase/src' to sys.path

In [3]:
checkpoint = "DeepWokLab/bert-tiny"
tokenizer_checkpoint = "DeepWokLab/bert-tiny"
dataset_name = "imdb"

## Sentiment Analysis with the IMDb Dataset

The IMDB dataset, introduced in [this 2011 paper](https://aclanthology.org/P11-1015/) from Stanford, is commonly used for sentiment analysis in the Natural Language Processing (NLP) community. This is a collection of 50k movie reviews from the IMDb website, labelled as either "positive" or "negative". Here is an example of a positive review:

> I turned over to this film in the middle of the night and very nearly skipped right passed it. It was only because there was nothing else on that I decided to watch it. In the end, I thought it was great.<br /><br />An interesting storyline, good characters, a clever script and brilliant directing makes this a fine film to sit down and watch. This was, in fact, the first I'd heard of this movie, but I would have been happy to have paid money to see this at the cinema.<br /><br />My IMDB Rating : 8 out of 10<br /><br />

And a negative review:

> its a totally average film with a few semi-alright action sequences that make the plot seem a little better and remind the viewer of the classic van dam films. parts of the plot don't make sense and seem to be added in to use up time. the end plot is that of a very basic type that doesn't leave the viewer guessing and any twists are obvious from the beginning. the end scene with the flask backs don't make sense as they are added in and seem to have little relevance to the history of van dam's character. not really worth watching again, bit disappointed in the end production, even though it is apparent it was shot on a low budget certain shots and sections in the film are of poor directed quality

The dataset is available from HuggingFace through the ``datasets`` library. We use the `get_tokenized_dataset` utility in Mase to automatically tokenize it.

In [4]:
from chop.tools import get_tokenized_dataset

dataset, tokenizer = get_tokenized_dataset(
    dataset=dataset_name,
    checkpoint=tokenizer_checkpoint,
    return_tokenizer=True,
)

/usr/local/lib/python3.12/dist-packages/torch/cuda/__init__.py:63: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]
Flax classes are deprecated and will be removed in Diffusers v1.0.0. We recommend migrating to PyTorch classes or pinning your version of Diffusers.
Flax classes are deprecated and will be removed in Diffusers v1.0.0. We recommend migrating to PyTorch classes or pinning your version of Diffusers.
INFO     Tokenizing dataset imdb with AutoTokenizer for DeepWokLab/bert-tiny.
/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

README.md: 0.00B [00:00, ?B/s]

plain_text/train-00000-of-00001.parquet:   0%|          | 0.00/21.0M [00:00<?, ?B/s]

plain_text/test-00000-of-00001.parquet:   0%|          | 0.00/20.5M [00:00<?, ?B/s]

plain_text/unsupervised-00000-of-00001.p(…):   0%|          | 0.00/42.0M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/25000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/25000 [00:00<?, ? examples/s]

Generating unsupervised split:   0%|          | 0/50000 [00:00<?, ? examples/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

Map:   0%|          | 0/25000 [00:00<?, ? examples/s]

Map:   0%|          | 0/25000 [00:00<?, ? examples/s]

Map:   0%|          | 0/50000 [00:00<?, ? examples/s]

## Generate a MaseGraph with Custom Arguments

By inspecting the implementation of the Bert model in HuggingFace, we can see the forward function has a signature similar to the following.

```python
    class BertForSequenceClassification(BertPreTrainedModel):
        def __init__(self, config):
            super().__init__(config)
            self.bert = BertModel(config)
            ...

        def forward(
            self,
            input_ids: Optional[torch.Tensor] = None,
            attention_mask: Optional[torch.Tensor] = None,
            token_type_ids: Optional[torch.Tensor] = None,
            position_ids: Optional[torch.Tensor] = None,
            head_mask: Optional[torch.Tensor] = None,
            inputs_embeds: Optional[torch.Tensor] = None,
            labels: Optional[torch.Tensor] = None,
            output_attentions: Optional[bool] = None,
            output_hidden_states: Optional[bool] = None,
            return_dict: Optional[bool] = None,
        ) -> Union[Tuple[torch.Tensor], SequenceClassifierOutput]:
            ...
```

By default, the MaseGraph constructor chooses to use the `input_ids` argument, ignoring the other optional arguments. However, you can specify which inputs to drive during symbolic tracing using the `hf_input_names` argument. In the following cell, we also drive the `attention_mask` and `labels` inputs. By specifying the `labels` argument, we include a `nn.CrossEntropyLoss` module at the end of the model to calculate the loss directly.

> **Task:** Remove the `attention_mask` and `labels` arguments from the `hf_input_names` list and re-run the following cell. Use `mg.draw()` to visualize the graph in each case. Can you see any changes in the graph topology? Can you explain why this happens?

In [5]:
from transformers import AutoModelForSequenceClassification

from chop import MaseGraph
import chop.passes as passes

model = AutoModelForSequenceClassification.from_pretrained(checkpoint)
model.config.problem_type = "single_label_classification"

mg = MaseGraph(
    model,
    hf_input_names=[
        "input_ids",
        "attention_mask",
        "labels",
    ],
)

mg, _ = passes.init_metadata_analysis_pass(mg)
mg, _ = passes.add_common_metadata_analysis_pass(mg)

config.json:   0%|          | 0.00/622 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/17.5M [00:00<?, ?B/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at DeepWokLab/bert-tiny and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
`past_key_values` were not specified as input names, but model.config.use_cache = True. Setting model.config.use_cache = False.
W0202 14:23:03.883000 911 torch/fx/_symbolic_trace.py:52] is_fx_tracing will return true for both fx.symbolic_trace and torch.export. Please use is_fx_tracing_symbolic_tracing() for specifically fx.symbolic_trace or torch.compiler.is_compiling() for specifically torch.export/compile.
INFO     Getting dummy input for DeepWokLab/bert-tiny.

tensor([[ 101, 9932, 2089, 2202, 2058, 1996, 2088, 2028, 2154,  102],
        [ 101, 2023, 2003, 2339, 2017, 2323, 4553, 4748, 4877,  102]])
tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
tensor([[ 101, 9932, 2089, 2202, 2058, 1996, 2088, 2028, 2154,  102],
        [ 101, 2023, 2003, 2339, 2017, 2323, 4553, 4748, 4877,  102]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]],


        [[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]]])
tensor([[[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]],


        [[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]]])
tensor([[[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]]])
tensor([[[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]]])
tensor([[[ 0.7973,  0.0109, -8.8405,  ...,  1.4170,  0.1046, -0.1551],
         [-1.1766,  1.2879, -1.0986,  ...,  0.4749, -0.5899,  0.8746],
         [-2.0560,  0.7748, -0.8909,  ..., -0.4034,  0.5352, -1.3657],
         ...,
         [ 0.2317, -0.7896,  0.9634,  ..., -0.8037,  0.4834, -0.5868],
         [ 0.0243, -1.0235, -1.2771,  ..., -2.2378,  1.8530,  0.1558],
         [-1.3637,  0.7055, -0.2177,  ...,  0.3557, -0.3971, -0.3107]],

        [[ 0.7973,  0.0109, -8.8405,  ...,  1.4170,  0.1046, -0.1551],
         [-2.6940,  0.6198, -0.4564,  ..., -1.4367, -1.5705, -3.1260],
         [-1.7524,  0.8535, -0.2155,  ..., -0.5222, -1.2430, -1.7199],
         ...,
         [-0.0347,  0.7446,  1.4462,  ..., -1.1578, -2.6197,  0.2612],
         [ 2.4334, -0.3068,  0.8250,  ...,  0.1475,  0.1790,  2.2907],
         [-1.3637,  0.7055, -0.2177,  ...,  0.3557, -0.3971, -0.3107]]],
       grad_fn=<NativeLayerNormBackward0>)
tensor([[[ 9.7740e-01,  2.5482e-03, -5.2921e-01,  ...,  1.4757e-01,
           1.8900e-01,  2.8282e-01],
         [-3.5020e-02, -6.1047e-02, -1.0465e-01,  ..., -8.1892e-01,
           1.1978e+00,  2.1808e+00],
         [ 4.3982e-01, -1.9602e+00, -6.8830e-01,  ..., -6.3025e-01,
          -1.5967e-01,  1.3284e+00],
         ...,
         [ 1.4783e+00,  1.0907e-01, -1.5222e+00,  ..., -3.0983e-01,
          -1.2971e-01,  1.1265e+00],
         [ 1.5890e+00, -1.6859e+00,  7.8703e-01,  ..., -1.3174e+00,
           2.2258e-01,  8.8157e-01],
         [-3.7517e-01,  1.5191e+00, -2.6796e-01,  ..., -1.6159e+00,
           7.2677e-02,  1.1724e-01]],

        [[ 9.7740e-01,  2.5482e-03, -5.2921e-01,  ...,  1.4757e-01,
           1.8900e-01,  2.8282e-01],
         [-4.4781e-01, -7.9224e-01, -2.1741e+00,  ..., -5.9181e-01,
           1.4373e+00,  2.4267e+00],
         [-2.5942e-01,  9.7163e-01, -3.2928e+00,  ..., -5.9773e-01,
          -3.0482e-01,  1.4038e+00],
         ...,
         [ 5.1575e-02,  3.5218e-01, -3.8926e-01,  ..., -1.1508e+00,
           7.5490e-01,  8.2911e-01],
         [ 1.6107e+00,  6.8170e-02,  9.2537e-01,  ..., -1.5233e+00,
          -6.0733e-01,  3.3097e-01],
         [-3.7517e-01,  1.5191e+00, -2.6796e-01,  ..., -1.6159e+00,
           7.2677e-02,  1.1724e-01]]], grad_fn=<ViewBackward0>)
tensor([[[ 9.7740e-01,  2.5482e-03, -5.2921e-01,  ...,  1.4757e-01,
           1.8900e-01,  2.8282e-01],
         [-3.5020e-02, -6.1047e-02, -1.0465e-01,  ..., -8.1892e-01,
           1.1978e+00,  2.1808e+00],
         [ 4.3982e-01, -1.9602e+00, -6.8830e-01,  ..., -6.3025e-01,
          -1.5967e-01,  1.3284e+00],
         ...,
         [ 1.4783e+00,  1.0907e-01, -1.5222e+00,  ..., -3.0983e-01,
          -1.2971e-01,  1.1265e+00],
         [ 1.5890e+00, -1.6859e+00,  7.8703e-01,  ..., -1.3174e+00,
           2.2258e-01,  8.8157e-01],
         [-3.7517e-01,  1.5191e+00, -2.6796e-01,  ..., -1.6159e+00,
           7.2677e-02,  1.1724e-01]],

        [[ 9.7740e-01,  2.5482e-03, -5.2921e-01,  ...,  1.4757e-01,
           1.8900e-01,  2.8282e-01],
         [-4.4781e-01, -7.9224e-01, -2.1741e+00,  ..., -5.9181e-01,
           1.4373e+00,  2.4267e+00],
         [-2.5942e-01,  9.7163e-01, -3.2928e+00,  ..., -5.9773e-01,
          -3.0482e-01,  1.4038e+00],
         ...,
         [ 5.1575e-02,  3.5218e-01, -3.8926e-01,  ..., -1.1508e+00,
           7.5490e-01,  8.2911e-01],
         [ 1.6107e+00,  6.8170e-02,  9.2537e-01,  ..., -1.5233e+00,
          -6.0733e-01,  3.3097e-01],
         [-3.7517e-01,  1.5191e+00, -2.6796e-01,  ..., -1.6159e+00,
           7.2677e-02,  1.1724e-01]]], grad_fn=<ViewBackward0>)
tensor([[[[ 9.7740e-01,  2.5482e-03, -5.2921e-01,  ..., -5.2614e-01,
           -3.5687e-01, -2.6793e-01],
          [ 2.0335e-01, -5.4534e-01,  3.0686e-01,  ...,  1.4757e-01,
            1.8900e-01,  2.8282e-01]],

         [[-3.5020e-02, -6.1047e-02, -1.0465e-01,  ..., -2.0138e+00,
            4.5529e-01, -7.8171e-01],
          [ 1.1969e+00,  1.6337e+00,  2.5047e-01,  ..., -8.1892e-01,
            1.1978e+00,  2.1808e+00]],

         [[ 4.3982e-01, -1.9602e+00, -6.8830e-01,  ..., -2.2501e-01,
            7.2290e-02, -1.8290e+00],
          [ 8.9952e-01,  1.0029e+00,  7.4536e-04,  ..., -6.3025e-01,
           -1.5967e-01,  1.3284e+00]],

         ...,

         [[ 1.4783e+00,  1.0907e-01, -1.5222e+00,  ...,  1.1867e+00,
           -1.3561e+00,  6.5158e-01],
          [ 9.5466e-01,  4.5887e-01,  7.8078e-01,  ..., -3.0983e-01,
           -1.2971e-01,  1.1265e+00]],

         [[ 1.5890e+00, -1.6859e+00,  7.8703e-01,  ...,  6.5467e-01,
           -6.8451e-01,  6.5081e-01],
          [ 7.0729e-01,  1.4499e+00, -1.5089e-01,  ..., -1.3174e+00,
            2.2258e-01,  8.8157e-01]],

         [[-3.7517e-01,  1.5191e+00, -2.6796e-01,  ...,  3.3130e-01,
           -3.2756e-01, -6.3130e-01],
          [ 8.6773e-01,  2.0996e-01, -3.4332e-01,  ..., -1.6159e+00,
            7.2677e-02,  1.1724e-01]]],


        [[[ 9.7740e-01,  2.5482e-03, -5.2921e-01,  ..., -5.2614e-01,
           -3.5687e-01, -2.6793e-01],
          [ 2.0335e-01, -5.4534e-01,  3.0686e-01,  ...,  1.4757e-01,
            1.8900e-01,  2.8282e-01]],

         [[-4.4781e-01, -7.9224e-01, -2.1741e+00,  ...,  1.7508e+00,
           -3.6708e-01, -1.3251e+00],
          [ 7.9208e-01, -1.3537e-01,  2.3756e-01,  ..., -5.9181e-01,
            1.4373e+00,  2.4267e+00]],

         [[-2.5942e-01,  9.7163e-01, -3.2928e+00,  ..., -9.6646e-01,
           -4.8876e-01, -1.4426e+00],
          [ 1.0250e+00, -6.9093e-01, -1.2734e+00,  ..., -5.9773e-01,
           -3.0482e-01,  1.4038e+00]],

         ...,

         [[ 5.1575e-02,  3.5218e-01, -3.8926e-01,  ..., -1.2252e-02,
            1.0394e+00,  4.2402e-01],
          [-4.7386e-01,  2.6401e+00,  1.7024e+00,  ..., -1.1508e+00,
            7.5490e-01,  8.2911e-01]],

         [[ 1.6107e+00,  6.8170e-02,  9.2537e-01,  ..., -6.1665e-01,
            2.7627e-01, -1.2083e+00],
          [ 9.3395e-01, -9.7541e-01, -2.5442e-02,  ..., -1.5233e+00,
           -6.0733e-01,  3.3097e-01]],

         [[-3.7517e-01,  1.5191e+00, -2.6796e-01,  ...,  3.3130e-01,
           -3.2756e-01, -6.3130e-01],
          [ 8.6773e-01,  2.0996e-01, -3.4332e-01,  ..., -1.6159e+00,
            7.2677e-02,  1.1724e-01]]]], grad_fn=<ViewBackward0>)
tensor([[[-0.1709,  0.5230, -0.8713,  ..., -1.3382,  0.5892,  0.4026],
         [-0.5842,  0.9588,  1.5642,  ..., -1.0731, -0.7330,  0.3132],
         [-0.8601, -1.3756,  0.5042,  ..., -0.0476,  0.2650,  1.2150],
         ...,
         [ 0.0520,  1.1719, -1.5471,  ..., -0.7894,  0.1419,  1.6964],
         [ 0.7654, -1.5053, -0.4142,  ..., -1.4622, -0.8975,  1.4576],
         [-1.2008, -0.6008, -1.4608,  ..., -1.2105, -0.4289,  0.3827]],

        [[-0.1709,  0.5230, -0.8713,  ..., -1.3382,  0.5892,  0.4026],
         [-1.3806,  0.2626, -0.5207,  ..., -1.6714, -0.0554,  1.0225],
         [-1.7116,  1.8788, -2.5695,  ..., -0.6958,  0.5728,  0.5461],
         ...,
         [-1.3246,  1.2196, -0.3034,  ..., -1.1955, -0.6708,  0.5128],
         [ 0.9854,  0.8260,  0.2892,  ..., -0.6428,  0.3637,  0.4339],
         [-1.2008, -0.6008, -1.4608,  ..., -1.2105, -0.4289,  0.3827]]],
       grad_fn=<ViewBackward0>)
tensor([[[-0.1709,  0.5230, -0.8713,  ..., -1.3382,  0.5892,  0.4026],
         [-0.5842,  0.9588,  1.5642,  ..., -1.0731, -0.7330,  0.3132],
         [-0.8601, -1.3756,  0.5042,  ..., -0.0476,  0.2650,  1.2150],
         ...,
         [ 0.0520,  1.1719, -1.5471,  ..., -0.7894,  0.1419,  1.6964],
         [ 0.7654, -1.5053, -0.4142,  ..., -1.4622, -0.8975,  1.4576],
         [-1.2008, -0.6008, -1.4608,  ..., -1.2105, -0.4289,  0.3827]],

        [[-0.1709,  0.5230, -0.8713,  ..., -1.3382,  0.5892,  0.4026],
         [-1.3806,  0.2626, -0.5207,  ..., -1.6714, -0.0554,  1.0225],
         [-1.7116,  1.8788, -2.5695,  ..., -0.6958,  0.5728,  0.5461],
         ...,
         [-1.3246,  1.2196, -0.3034,  ..., -1.1955, -0.6708,  0.5128],
         [ 0.9854,  0.8260,  0.2892,  ..., -0.6428,  0.3637,  0.4339],
         [-1.2008, -0.6008, -1.4608,  ..., -1.2105, -0.4289,  0.3827]]],
       grad_fn=<ViewBackward0>)
tensor([[[[-0.1709,  0.5230, -0.8713,  ...,  0.4365,  0.6238, -0.9414],
          [-1.3731,  1.1521,  0.1321,  ..., -1.3382,  0.5892,  0.4026]],

         [[-0.5842,  0.9588,  1.5642,  ..., -1.5431,  0.4999, -1.1350],
          [ 0.9615,  0.8694,  0.0998,  ..., -1.0731, -0.7330,  0.3132]],

         [[-0.8601, -1.3756,  0.5042,  ...,  0.9764, -0.8321, -1.0204],
          [ 1.5175,  1.1454,  0.7791,  ..., -0.0476,  0.2650,  1.2150]],

         ...,

         [[ 0.0520,  1.1719, -1.5471,  ...,  1.9402, -1.1294,  0.4793],
          [ 1.0053,  0.8099,  1.6415,  ..., -0.7894,  0.1419,  1.6964]],

         [[ 0.7654, -1.5053, -0.4142,  ...,  1.7455, -0.7326,  1.5248],
          [ 1.0806,  1.1457,  2.2163,  ..., -1.4622, -0.8975,  1.4576]],

         [[-1.2008, -0.6008, -1.4608,  ...,  2.0905,  1.8849, -1.5708],
          [ 1.9999,  0.3493, -0.8524,  ..., -1.2105, -0.4289,  0.3827]]],


        [[[-0.1709,  0.5230, -0.8713,  ...,  0.4365,  0.6238, -0.9414],
          [-1.3731,  1.1521,  0.1321,  ..., -1.3382,  0.5892,  0.4026]],

         [[-1.3806,  0.2626, -0.5207,  ...,  1.6517, -0.2316, -1.3171],
          [ 0.6812, -0.0090,  0.3803,  ..., -1.6714, -0.0554,  1.0225]],

         [[-1.7116,  1.8788, -2.5695,  ...,  0.4927, -0.4850, -1.0645],
          [ 1.2646,  1.6481,  0.9055,  ..., -0.6958,  0.5728,  0.5461]],

         ...,

         [[-1.3246,  1.2196, -0.3034,  ...,  1.2747,  1.2353,  0.2825],
          [ 1.5373,  0.8648,  0.6062,  ..., -1.1955, -0.6708,  0.5128]],

         [[ 0.9854,  0.8260,  0.2892,  ...,  1.3848, -0.0103, -1.0700],
          [ 1.3827,  2.9809,  0.0276,  ..., -0.6428,  0.3637,  0.4339]],

         [[-1.2008, -0.6008, -1.4608,  ...,  2.0905,  1.8849, -1.5708],
          [ 1.9999,  0.3493, -0.8524,  ..., -1.2105, -0.4289,  0.3827]]]],
       grad_fn=<ViewBackward0>)
tensor([[[-0.0123,  0.5761,  0.2209,  ..., -0.1027,  1.1061, -2.5200],
         [-1.1465, -1.5578, -0.6984,  ...,  1.0310,  0.4824, -0.2291],
         [-1.0361, -1.8192, -2.3055,  ...,  1.5286, -1.5941,  1.1762],
         ...,
         [-0.7992,  0.0886,  0.4887,  ..., -1.7941,  0.4835,  1.3780],
         [-1.4692, -0.9135, -0.2802,  ..., -0.9691,  0.3500,  1.8863],
         [-0.5760, -0.0452,  0.4230,  ..., -0.7179, -0.7858,  1.6879]],

        [[-0.0123,  0.5761,  0.2209,  ..., -0.1027,  1.1061, -2.5200],
         [-0.3700, -1.9754, -0.7315,  ...,  0.2293,  0.6996,  3.1299],
         [-0.6252,  0.2879, -1.4036,  ..., -2.0560, -2.4623, -0.9584],
         ...,
         [-1.1306, -1.4343, -1.4422,  ..., -1.6115, -0.0475,  1.3975],
         [-0.9816, -1.4909, -1.0086,  ..., -0.9284,  0.5260,  1.5330],
         [-0.5760, -0.0452,  0.4230,  ..., -0.7179, -0.7858,  1.6879]]],
       grad_fn=<ViewBackward0>)
tensor([[[-0.0123,  0.5761,  0.2209,  ..., -0.1027,  1.1061, -2.5200],
         [-1.1465, -1.5578, -0.6984,  ...,  1.0310,  0.4824, -0.2291],
         [-1.0361, -1.8192, -2.3055,  ...,  1.5286, -1.5941,  1.1762],
         ...,
         [-0.7992,  0.0886,  0.4887,  ..., -1.7941,  0.4835,  1.3780],
         [-1.4692, -0.9135, -0.2802,  ..., -0.9691,  0.3500,  1.8863],
         [-0.5760, -0.0452,  0.4230,  ..., -0.7179, -0.7858,  1.6879]],

        [[-0.0123,  0.5761,  0.2209,  ..., -0.1027,  1.1061, -2.5200],
         [-0.3700, -1.9754, -0.7315,  ...,  0.2293,  0.6996,  3.1299],
         [-0.6252,  0.2879, -1.4036,  ..., -2.0560, -2.4623, -0.9584],
         ...,
         [-1.1306, -1.4343, -1.4422,  ..., -1.6115, -0.0475,  1.3975],
         [-0.9816, -1.4909, -1.0086,  ..., -0.9284,  0.5260,  1.5330],
         [-0.5760, -0.0452,  0.4230,  ..., -0.7179, -0.7858,  1.6879]]],
       grad_fn=<ViewBackward0>)
tensor([[[[-0.0123,  0.5761,  0.2209,  ..., -0.1457, -0.7538,  0.1761],
          [-0.0705,  0.9215,  0.7990,  ..., -0.1027,  1.1061, -2.5200]],

         [[-1.1465, -1.5578, -0.6984,  ...,  0.0289, -2.1112, -0.8728],
          [ 0.6506, -1.6966,  1.4463,  ...,  1.0310,  0.4824, -0.2291]],

         [[-1.0361, -1.8192, -2.3055,  ..., -0.2195, -1.1732,  0.3182],
          [-0.5841, -0.0227,  3.0901,  ...,  1.5286, -1.5941,  1.1762]],

         ...,

         [[-0.7992,  0.0886,  0.4887,  ...,  0.7859, -1.0127, -0.2676],
          [-0.3055,  0.6270, -3.0705,  ..., -1.7941,  0.4835,  1.3780]],

         [[-1.4692, -0.9135, -0.2802,  ...,  0.1197, -0.7532,  0.0731],
          [ 0.6096, -1.0893, -0.6959,  ..., -0.9691,  0.3500,  1.8863]],

         [[-0.5760, -0.0452,  0.4230,  ...,  0.8851,  0.3078,  0.8106],
          [-1.1804,  0.9512,  0.3169,  ..., -0.7179, -0.7858,  1.6879]]],


        [[[-0.0123,  0.5761,  0.2209,  ..., -0.1457, -0.7538,  0.1761],
          [-0.0705,  0.9215,  0.7990,  ..., -0.1027,  1.1061, -2.5200]],

         [[-0.3700, -1.9754, -0.7315,  ...,  0.5756, -1.5559,  0.0326],
          [ 1.4229,  2.3970, -0.4516,  ...,  0.2293,  0.6996,  3.1299]],

         [[-0.6252,  0.2879, -1.4036,  ...,  0.5306, -0.5608,  1.1861],
          [-2.5980,  0.2673,  3.3016,  ..., -2.0560, -2.4623, -0.9584]],

         ...,

         [[-1.1306, -1.4343, -1.4422,  ...,  0.3918, -1.5336, -0.5026],
          [ 1.8587,  0.8501, -1.2402,  ..., -1.6115, -0.0475,  1.3975]],

         [[-0.9816, -1.4909, -1.0086,  ...,  0.2956,  0.0351, -1.0685],
          [-0.6594, -0.0133, -1.1863,  ..., -0.9284,  0.5260,  1.5330]],

         [[-0.5760, -0.0452,  0.4230,  ...,  0.8851,  0.3078,  0.8106],
          [-1.1804,  0.9512,  0.3169,  ..., -0.7179, -0.7858,  1.6879]]]],
       grad_fn=<ViewBackward0>)
tensor([[[[-0.5911, -0.4682, -0.4314,  ...,  0.0366, -1.0405, -0.0579],
          [-1.1141, -1.4785, -0.6477,  ...,  0.0631, -1.9950, -0.7912],
          [-0.7059, -0.9954, -1.3923,  ..., -0.1557, -0.9998,  0.2774],
          ...,
          [-0.6300,  0.1252,  0.3486,  ...,  0.5692, -0.9417, -0.1399],
          [-1.0593, -0.6395, -0.3343,  ...,  0.0571, -0.7842,  0.1042],
          [-0.2081,  0.2785,  0.0613,  ..., -0.0353, -0.8389, -0.0026]],

         [[-0.3266,  0.6360,  0.0214,  ...,  0.1677,  0.3883,  0.4382],
          [-0.6299,  0.6012,  0.7379,  ...,  0.2989, -0.1569,  0.9508],
          [-0.4097,  0.6374, -0.1589,  ...,  0.0258, -0.0364,  0.9990],
          ...,
          [-0.0088,  0.1378, -0.4819,  ..., -0.1261,  0.2908,  1.0980],
          [-0.5584,  0.9932, -0.1105,  ...,  0.2486,  0.4005,  0.6046],
          [-0.4516,  0.8092, -0.0513,  ...,  0.1182,  0.4294,  0.4781]]],


        [[[-0.6850, -0.2168, -0.6087,  ...,  0.1402, -0.7267, -0.1502],
          [-0.2084, -0.1325, -0.1151,  ...,  0.0938, -0.8963,  0.1296],
          [-0.3665,  0.3408, -0.6133,  ...,  0.1938, -0.6681,  0.5929],
          ...,
          [-1.0985, -1.2861, -1.2531,  ...,  0.3609, -1.4022, -0.4444],
          [-0.9787, -1.4207, -0.9908,  ...,  0.2989, -0.0159, -1.0060],
          [-0.1970,  0.2371, -0.0115,  ...,  0.0049, -0.8135,  0.1201]],

         [[ 0.0907,  0.7927, -0.0524,  ..., -0.4610, -0.4295,  0.4391],
          [-0.2352,  1.0586, -0.1117,  ..., -0.4943, -0.6546,  0.6617],
          [ 0.8269,  1.7861, -1.1207,  ..., -0.0885,  0.2791,  1.4721],
          ...,
          [-0.1038,  0.9623, -0.7062,  ..., -0.3340, -0.3050,  0.8792],
          [ 0.0507,  0.6634, -0.2642,  ..., -0.4959, -0.7944,  0.7687],
          [ 0.3364,  0.9047, -0.2037,  ..., -0.3705, -0.2893,  0.6787]]]],
       grad_fn=<ScaledDotProductFlashAttentionForCpuBackward0>)
tensor([[[[-0.5911, -0.4682, -0.4314,  ...,  0.0366, -1.0405, -0.0579],
          [-0.3266,  0.6360,  0.0214,  ...,  0.1677,  0.3883,  0.4382]],

         [[-1.1141, -1.4785, -0.6477,  ...,  0.0631, -1.9950, -0.7912],
          [-0.6299,  0.6012,  0.7379,  ...,  0.2989, -0.1569,  0.9508]],

         [[-0.7059, -0.9954, -1.3923,  ..., -0.1557, -0.9998,  0.2774],
          [-0.4097,  0.6374, -0.1589,  ...,  0.0258, -0.0364,  0.9990]],

         ...,

         [[-0.6300,  0.1252,  0.3486,  ...,  0.5692, -0.9417, -0.1399],
          [-0.0088,  0.1378, -0.4819,  ..., -0.1261,  0.2908,  1.0980]],

         [[-1.0593, -0.6395, -0.3343,  ...,  0.0571, -0.7842,  0.1042],
          [-0.5584,  0.9932, -0.1105,  ...,  0.2486,  0.4005,  0.6046]],

         [[-0.2081,  0.2785,  0.0613,  ..., -0.0353, -0.8389, -0.0026],
          [-0.4516,  0.8092, -0.0513,  ...,  0.1182,  0.4294,  0.4781]]],


        [[[-0.6850, -0.2168, -0.6087,  ...,  0.1402, -0.7267, -0.1502],

## Full Supervised Finetuning (SFT)

Before training the model, let's inspect how many trainable parameters there are. If you're familiar with Keras, you might have used the `model.summary()` API before, but it's not as easy to do the same in Pytorch - luckily, Mase has a module-level pass with this functionality.

In [6]:
from chop.passes.module import report_trainable_parameters_analysis_pass

_, _ = report_trainable_parameters_analysis_pass(mg.model)

+-------------------------------------------------+------------------------+
| Submodule                                       |   Trainable Parameters |
+=================================================+========================+
| bert                                            |                4385920 |
+-------------------------------------------------+------------------------+
| bert.embeddings                                 |                3972864 |
+-------------------------------------------------+------------------------+
| bert.embeddings.word_embeddings                 |                3906816 |
+-------------------------------------------------+------------------------+
| bert.embeddings.token_type_embeddings           |                    256 |
+-------------------------------------------------+------------------------+
| bert.embeddings.position_embeddings             |                  65536 |
+-------------------------------------------------+------------------------+
| bert.embeddings.LayerNorm                       |                    256 |
+-------------------------------------------------+------------------------+
| bert.embeddings.dropout                         |                      0 |
+-------------------------------------------------+------------------------+
| bert.encoder                                    |                 396544 |
+-------------------------------------------------+------------------------+
| bert.encoder.layer                              |                 396544 |
+-------------------------------------------------+------------------------+
| bert.encoder.layer.0                            |                 198272 |
+-------------------------------------------------+------------------------+
| bert.encoder.layer.0.attention                  |                  66304 |
+-------------------------------------------------+------------------------+
| bert.encoder.layer.0.attention.self             |                  49536 |
+-------------------------------------------------+------------------------+
| bert.encoder.layer.0.attention.self.query       |                  16512 |
+-------------------------------------------------+------------------------+
| bert.encoder.layer.0.attention.self.key         |                  16512 |
+-------------------------------------------------+------------------------+
| bert.encoder.layer.0.attention.self.value       |                  16512 |
+-------------------------------------------------+------------------------+
| bert.encoder.layer.0.attention.output           |                  16768 |
+-------------------------------------------------+------------------------+
| bert.encoder.layer.0.attention.output.dense     |                  16512 |
+-------------------------------------------------+------------------------+
| bert.encoder.layer.0.attention.output.dropout   |                      0 |
+-------------------------------------------------+------------------------+
| bert.encoder.layer.0.attention.output.LayerNorm |                    256 |
+-------------------------------------------------+------------------------+
| bert.encoder.layer.0.intermediate               |                  66048 |
+-------------------------------------------------+------------------------+
| bert.encoder.layer.0.intermediate.dense         |                  66048 |
+-------------------------------------------------+------------------------+
| bert.encoder.layer.0.output                     |                  65920 |
+-------------------------------------------------+------------------------+
| bert.encoder.layer.0.output.dense               |                  65664 |
+-------------------------------------------------+------------------------+
| bert.encoder.layer.0.output.dropout             |                      0 |
+-------------------------------------------------+------------------------+
| bert.encoder.layer.0.output.LayerNorm           |                    256 |
+-------------------------------------------------+------------------------+
| bert.encoder.layer.1                            |                 198272 |
+-------------------------------------------------+------------------------+
| bert.encoder.layer.1.attention                  |                  66304 |
+-------------------------------------------------+------------------------+
| bert.encoder.layer.1.attention.self             |                  49536 |
+-------------------------------------------------+------------------------+
| bert.encoder.layer.1.attention.self.query       |                  16512 |
+-------------------------------------------------+------------------------+
| bert.encoder.layer.1.attention.self.key         |                  16512 |
+-------------------------------------------------+------------------------+
| bert.encoder.layer.1.attention.self.value       |                  16512 |
+-------------------------------------------------+------------------------+
| bert.encoder.layer.1.attention.output           |                  16768 |
+-------------------------------------------------+------------------------+
| bert.encoder.layer.1.attention.output.dense     |                  16512 |
+-------------------------------------------------+------------------------+
| bert.encoder.layer.1.attention.output.dropout   |                      0 |
+-------------------------------------------------+------------------------+
| bert.encoder.layer.1.attention.output.LayerNorm |                    256 |
+-------------------------------------------------+------------------------+
| bert.encoder.layer.1.intermediate               |                  66048 |
+-------------------------------------------------+------------------------+
| bert.encoder.layer.1.intermediate.dense         |                  66048 |
+-------------------------------------------------+------------------------+
| bert.encoder.layer.1.output                     |                  65920 |
+-------------------------------------------------+------------------------+
| bert.encoder.layer.1.output.dense               |                  65664 |
+-------------------------------------------------+------------------------+
| bert.encoder.layer.1.output.dropout             |                      0 |
+-------------------------------------------------+------------------------+
| bert.encoder.layer.1.output.LayerNorm           |                    256 |
+-------------------------------------------------+------------------------+
| bert.pooler                                     |                  16512 |
+-------------------------------------------------+------------------------+
| bert.pooler.dense                               |                  16512 |
+-------------------------------------------------+------------------------+
| bert.pooler.activation                          |                      0 |
+-------------------------------------------------+------------------------+
| dropout                                         |                      0 |
+-------------------------------------------------+------------------------+
| classifier                                      |                    258 |
+-------------------------------------------------+------------------------+
| crossentropyloss_0                              |                      0 |
+-------------------------------------------------+------------------------+

Total Trainable Parameters: 14480258

From this, we can see the majority of the trainable parameters are in the `Embedding` layer. We don't need to train this, so we freeze those parameters in the cell below.

In [7]:
for param in mg.model.bert.embeddings.parameters():
    param.requires_grad = False

To train the model, we rely on the `Trainer` class from the `transformers` library, which makes it easy to set up a training loop with any hardware configuration. The `get_trainer` utility in Mase handles assigning the training arguments to the `Trainer` class for common use cases, such as in this tutorial.

In [8]:
from chop.tools import get_trainer

trainer = get_trainer(
    model=mg.model,
    tokenized_dataset=dataset,
    tokenizer=tokenizer,
    evaluate_metric="accuracy",
)

Downloading builder script: 0.00B [00:00, ?B/s]

/content/drive/MyDrive/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Before running any fine tuning, let's see how the model performs out of the box. Without any fine-tuning, we can see the model just performs a random guess - there are two labels in the dataset, so this corresponds to an accuracy of around 50%.

In [9]:
# Evaluate accuracy
eval_results = trainer.evaluate()
print(f"Evaluation accuracy: {eval_results['eval_accuracy']}")

Evaluation accuracy: 0.50896

Now, run the cell below to execute a single training epoch with the current setup.

In [10]:
trainer.train()

TrainOutput(global_step=3125, training_loss=0.48224215087890626, metrics={'train_runtime': 51.6016, 'train_samples_per_second': 484.481, 'train_steps_per_second': 60.56, 'total_flos': 0.0, 'train_loss': 0.48224215087890626, 'epoch': 1.0})

Let's see how much accuracy we get after a single training epoch of full finetuning.

In [11]:
eval_results = trainer.evaluate()
print(f"Evaluation accuracy: {eval_results['eval_accuracy']}")

Evaluation accuracy: 0.81644

We can now export the SFT version of the model to be used in later tutorials.

In [12]:
from pathlib import Path

# mg.export(f"{Path.home()}/tutorial_2_sft")

mg.export("/content/drive/MyDrive/mase/src/tutorial_2_sft")

INFO     Exporting MaseGraph to /content/drive/MyDrive/mase/src/tutorial_2_sft.pt, /content/drive/MyDrive/mase/src/tutorial_2_sft.mz
INFO     Exporting GraphModule to /content/drive/MyDrive/mase/src/tutorial_2_sft.pt
INFO     Saving full model format
INFO     Exporting MaseMetadata to /content/drive/MyDrive/mase/src/tutorial_2_sft.mz
WARNING  Failed to pickle call_function node: finfo
WARNING  cannot pickle 'torch.finfo' object
WARNING  Failed to pickle call_function node: getattr_2
WARNING  cannot pickle 'torch.finfo' object

## Parameter Efficient Finetuning (PEFT) with LoRA

An alternative to full fine-tuning is Parameter Efficient Fine Tuning (PEFT), which uses a small number of trainable parameters to achieve similar performance. LoRA was proposed by a research team at Microsoft in 2021, as an efficient technique for PEFT.

<div style="text-align: center;">
    <img src="imgs/lora_adapter.png" alt="drawing" width="400"/>
</div>

Consider the standard equation of a linear layer:

$$
y = X W + b
$$

The LoRA method involves replacing this with the following, where A and B are low-rank matrices. We freeze the $W$ parameters, and only allow the optimizer to train the parameters in $A$ and $B$.

$$
y = X (W + AB) + b
$$

This enables us to achieve accuracies comparable to full fine tuning, while only training a fraction of the parameters. See [the paper](https://arxiv.org/abs/2106.09685) for more details. We can inject the LoRA adapter into the existing model using the `insert_lora_adapter_transform_pass` pass in Mase, as follows.

In [13]:
mg, _ = passes.insert_lora_adapter_transform_pass(
    mg,
    pass_args={
        "rank": 6,
        "alpha": 1.0,
        "dropout": 0.5,
    },
)

INFO     Replaced node: bert_encoder_layer_0_attention_self_query, target: bert.encoder.layer.0.attention.self.query with LoRALinear module.
INFO     Replaced node: bert_encoder_layer_0_attention_self_key, target: bert.encoder.layer.0.attention.self.key with LoRALinear module.
INFO     Replaced node: bert_encoder_layer_0_attention_self_value, target: bert.encoder.layer.0.attention.self.value with LoRALinear module.
INFO     Replaced node: bert_encoder_layer_0_attention_output_dense, target: bert.encoder.layer.0.attention.output.dense with LoRALinear module.
INFO     Replaced node: bert_encoder_layer_0_intermediate_dense, target: bert.encoder.layer.0.intermediate.dense with LoRALinear module.
INFO     Replaced node: bert_encoder_layer_0_output_dense, target: bert.encoder.layer.0.output.dense with LoRALinear module.
INFO     Replaced node: bert_encoder_layer_1_attention_self_query, target: bert.encoder.layer.1.attention.self.query with LoRALinear module.
INFO     Replaced node: bert_encoder_layer_1_attention_self_key, target: bert.encoder.layer.1.attention.self.key with LoRALinear module.
INFO     Replaced node: bert_encoder_layer_1_attention_self_value, target: bert.encoder.layer.1.attention.self.value with LoRALinear module.
INFO     Replaced node: bert_encoder_layer_1_attention_output_dense, target: bert.encoder.layer.1.attention.output.dense with LoRALinear module.
INFO     Replaced node: bert_encoder_layer_1_intermediate_dense, target: bert.encoder.layer.1.intermediate.dense with LoRALinear module.
INFO     Replaced node: bert_encoder_layer_1_output_dense, target: bert.encoder.layer.1.output.dense with LoRALinear module.
INFO     Replaced node: bert_pooler_dense, target: bert.pooler.dense with LoRALinear module.
INFO     Replaced node: classifier, target: classifier with LoRALinear module.

Similar to before, let's report the number of trainable parameters.

In [14]:
_, _ = report_trainable_parameters_analysis_pass(mg.model)

+-----------------------------------------------------+------------------------+
| Submodule                                           |   Trainable Parameters |
+=====================================================+========================+
| bert                                                |                 439808 |
+-----------------------------------------------------+------------------------+
| bert.embeddings                                     |                      0 |
+-----------------------------------------------------+------------------------+
| bert.embeddings.word_embeddings                     |                      0 |
+-----------------------------------------------------+------------------------+
| bert.embeddings.token_type_embeddings               |                      0 |
+-----------------------------------------------------+------------------------+
| bert.embeddings.position_embeddings                 |                      0 |
+-----------------------------------------------------+------------------------+
| bert.embeddings.LayerNorm                           |                      0 |
+-----------------------------------------------------+------------------------+
| bert.embeddings.dropout                             |                      0 |
+-----------------------------------------------------+------------------------+
| bert.encoder                                        |                 421888 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer                                  |                 421888 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.0                                |                 210944 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.0.attention                      |                  71936 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.0.attention.self                 |                  53760 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.0.attention.self.query           |                  17920 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.0.attention.self.query.linear    |                  16384 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.0.attention.self.query.lora_a    |                    768 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.0.attention.self.query.lora_b    |                    768 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.0.attention.self.query.dropout   |                      0 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.0.attention.self.key             |                  17920 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.0.attention.self.key.linear      |                  16384 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.0.attention.self.key.lora_a      |                    768 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.0.attention.self.key.lora_b      |                    768 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.0.attention.self.key.dropout     |                      0 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.0.attention.self.value           |                  17920 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.0.attention.self.value.linear    |                  16384 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.0.attention.self.value.lora_a    |                    768 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.0.attention.self.value.lora_b    |                    768 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.0.attention.self.value.dropout   |                      0 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.0.attention.output               |                  18176 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.0.attention.output.dense         |                  17920 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.0.attention.output.dense.linear  |                  16384 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.0.attention.output.dense.lora_a  |                    768 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.0.attention.output.dense.lora_b  |                    768 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.0.attention.output.dense.dropout |                      0 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.0.attention.output.dropout       |                      0 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.0.attention.output.LayerNorm     |                    256 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.0.intermediate                   |                  69376 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.0.intermediate.dense             |                  69376 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.0.intermediate.dense.linear      |                  65536 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.0.intermediate.dense.lora_a      |                    768 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.0.intermediate.dense.lora_b      |                   3072 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.0.intermediate.dense.dropout     |                      0 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.0.output                         |                  69632 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.0.output.dense                   |                  69376 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.0.output.dense.linear            |                  65536 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.0.output.dense.lora_a            |                   3072 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.0.output.dense.lora_b            |                    768 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.0.output.dense.dropout           |                      0 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.0.output.dropout                 |                      0 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.0.output.LayerNorm               |                    256 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.1                                |                 210944 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.1.attention                      |                  71936 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.1.attention.self                 |                  53760 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.1.attention.self.query           |                  17920 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.1.attention.self.query.linear    |                  16384 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.1.attention.self.query.lora_a    |                    768 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.1.attention.self.query.lora_b    |                    768 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.1.attention.self.query.dropout   |                      0 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.1.attention.self.key             |                  17920 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.1.attention.self.key.linear      |                  16384 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.1.attention.self.key.lora_a      |                    768 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.1.attention.self.key.lora_b      |                    768 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.1.attention.self.key.dropout     |                      0 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.1.attention.self.value           |                  17920 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.1.attention.self.value.linear    |                  16384 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.1.attention.self.value.lora_a    |                    768 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.1.attention.self.value.lora_b    |                    768 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.1.attention.self.value.dropout   |                      0 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.1.attention.output               |                  18176 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.1.attention.output.dense         |                  17920 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.1.attention.output.dense.linear  |                  16384 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.1.attention.output.dense.lora_a  |                    768 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.1.attention.output.dense.lora_b  |                    768 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.1.attention.output.dense.dropout |                      0 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.1.attention.output.dropout       |                      0 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.1.attention.output.LayerNorm     |                    256 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.1.intermediate                   |                  69376 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.1.intermediate.dense             |                  69376 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.1.intermediate.dense.linear      |                  65536 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.1.intermediate.dense.lora_a      |                    768 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.1.intermediate.dense.lora_b      |                   3072 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.1.intermediate.dense.dropout     |                      0 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.1.output                         |                  69632 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.1.output.dense                   |                  69376 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.1.output.dense.linear            |                  65536 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.1.output.dense.lora_a            |                   3072 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.1.output.dense.lora_b            |                    768 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.1.output.dense.dropout           |                      0 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.1.output.dropout                 |                      0 |
+-----------------------------------------------------+------------------------+
| bert.encoder.layer.1.output.LayerNorm               |                    256 |
+-----------------------------------------------------+------------------------+
| bert.pooler                                         |                  17920 |
+-----------------------------------------------------+------------------------+
| bert.pooler.dense                                   |                  17920 |
+-----------------------------------------------------+------------------------+
| bert.pooler.dense.linear                            |                  16384 |
+-----------------------------------------------------+------------------------+
| bert.pooler.dense.lora_a                            |                    768 |
+-----------------------------------------------------+------------------------+
| bert.pooler.dense.lora_b                            |                    768 |
+-----------------------------------------------------+------------------------+
| bert.pooler.dense.dropout                           |                      0 |
+-----------------------------------------------------+------------------------+
| bert.pooler.activation                              |                      0 |
+-----------------------------------------------------+------------------------+
| dropout                                             |                      0 |
+-----------------------------------------------------+------------------------+
| classifier                                          |                   1036 |
+-----------------------------------------------------+------------------------+
| classifier.linear                                   |                    256 |
+-----------------------------------------------------+------------------------+
| classifier.lora_a                                   |                    768 |
+-----------------------------------------------------+------------------------+
| classifier.lora_b                                   |                     12 |
+-----------------------------------------------------+------------------------+
| classifier.dropout                                  |                      0 |
+-----------------------------------------------------+------------------------+
| crossentropyloss_0                                  |                      0 |
+-----------------------------------------------------+------------------------+

Total Trainable Parameters: 3169816

In this case, LoRA reduces the number of trainable parameters by $4.5\times$! We'll run a few more training epochs and evaluate the resulting accuracy.

In [15]:
trainer = get_trainer(
    model=mg.model,
    tokenized_dataset=dataset,
    tokenizer=tokenizer,
    evaluate_metric="accuracy",
    num_train_epochs=1,
)
trainer.train()

# Evaluate accuracy
eval_results = trainer.evaluate()
print(f"Evaluation accuracy: {eval_results['eval_accuracy']}")

/content/drive/MyDrive/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Evaluation accuracy: 0.83496

After training is finished, we can run the `fuse_lora_weights_transform_pass` pass to optimize the model for inference. This pass replaces each `LoRALinear` instance with an `nn.Linear` module, where the $AB$ product added to the original weights matrix. This incurs less kernel invocations when deploying the model, which reduces inference runtime.

In [16]:
mg, _ = passes.fuse_lora_weights_transform_pass(mg)
eval_results = trainer.evaluate()

INFO     Fusing LoRALinear weights for bert.encoder.layer.0.attention.self.query.
INFO     Fusing LoRALinear weights for bert.encoder.layer.0.attention.self.key.
INFO     Fusing LoRALinear weights for bert.encoder.layer.0.attention.self.value.
INFO     Fusing LoRALinear weights for bert.encoder.layer.0.attention.output.dense.
INFO     Fusing LoRALinear weights for bert.encoder.layer.0.intermediate.dense.
INFO     Fusing LoRALinear weights for bert.encoder.layer.0.output.dense.
INFO     Fusing LoRALinear weights for bert.encoder.layer.1.attention.self.query.
INFO     Fusing LoRALinear weights for bert.encoder.layer.1.attention.self.key.
INFO     Fusing LoRALinear weights for bert.encoder.layer.1.attention.self.value.
INFO     Fusing LoRALinear weights for bert.encoder.layer.1.attention.output.dense.
INFO     Fusing LoRALinear weights for bert.encoder.layer.1.intermediate.dense.
INFO     Fusing LoRALinear weights for bert.encoder.layer.1.output.dense.
INFO     Fusing LoRALinear weights for bert.pooler.dense.
INFO     Fusing LoRALinear weights for classifier.

In [17]:
print(f"Evaluation accuracy: {eval_results['eval_accuracy']}")

Evaluation accuracy: 0.83496

Finally, export the finetuned model to be used in future tutorials.

In [18]:
from pathlib import Path

# mg.export(f"{Path.home()}/tutorial_2_lora")
mg.export("/content/drive/MyDrive/mase/src/tutorial_2_lora")

INFO     Exporting MaseGraph to /content/drive/MyDrive/mase/src/tutorial_2_lora.pt, /content/drive/MyDrive/mase/src/tutorial_2_lora.mz
INFO     Exporting GraphModule to /content/drive/MyDrive/mase/src/tutorial_2_lora.pt
INFO     Saving full model format
INFO     Exporting MaseMetadata to /content/drive/MyDrive/mase/src/tutorial_2_lora.mz
WARNING  Failed to pickle call_function node: finfo
WARNING  cannot pickle 'torch.finfo' object
WARNING  Failed to pickle call_function node: getattr_2
WARNING  cannot pickle 'torch.finfo' object

## Conclusion

By adjusting the rank number of LoRA, we can control the trade-off between memory usage and fine-tuned accuracy. Such parameter-efficient fine-tuning techniques are very useful in the area of large language models (LLMs), where the memory requirement for training is a significant bottleneck.